<?php

/**
 * @file
 * Contains hierarchical_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hierarchical_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hierarchical_config module.
    case 'help.page.hierarchical_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}
